name: CI Workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 # Or your preferred version
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing contents of /github/workspace:"
          ls -laR /github/workspace

      - name: Run Molecule Tests
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug --base-config molecule/_shared/base.yml
          molecule_command: test
          molecule_args: --scenario-name default
          molecule_working_dir: collections/ansible_collections/sample_namespace/sample_collection/extensions # Adjust this after checking the ls output