on: push

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "ansible-devspaces-demo/collections/ansible_collections/sample_namespace/sample_collection/extensions/molecule.yml"
      - uses: gofrolist/molecule-action@v2